apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsone-project-deployment
  labels:
    app: devops
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-project
        image: azmiabad/devops:latest
        ports:
        - containerPort: 80
